### ISSUE TITLE
payment integration / content subscriptions

### ISSUE THREAD

**Issue by sable-starflower** [sable-starflower/starflower.space#16]
## goals

some kind of way to link payments with followers so that they can subscribe to posted content. 

- support multiple payment processors
- support cryptocurrencies
- support manual subscription controls (so that subscriptions can be paid out-of-band via e.g. amazon wishlists)

## tasks

- [ ] persistence schema that associates payment accounts with fediverse accounts
- [ ] persistence schema that tracks whether an account is current with a subscription to another account
- [ ] api integration to check if payments are current for a given account
- [ ] auto-approve follow requests if payments are current for that account
- [ ] auto-remove followers if their subscription lapses

## resources / documentation

- [list of payment providers](https://sexworkerhelpfuls.com/payment-options)

## possible future extensions

- api to view / modify subscriptions (this could be used for a ui dashboard for manual subscription controls)
