### ISSUE TITLE
consolidate my masto repos

### ISSUE THREAD

**Issue by sable-starflower** [sable-starflower/starflower.space#48]
i had to create https://github.com/sable-starflower/mastodon in order to submit upstream PRs from it. i should:

- [ ] push all my changes from this repo into that one
- [ ] rename this one to something temporary
- [ ] rename that one to starflower.space
- [ ] make sure i can pull / deploy from the new repo to the starflower.space server
